spring.application.name=agendamento

server.port=8081
# ===============================
# CONFIGURAÇÃO DO POSTGRES
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:3333/banco
spring.datasource.username=usuario
spring.datasource.password=senha

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# INICIALIZAÇÃO DO BANCO
# ==========================================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# ==========================================
# SERVIDOR
# ==========================================